name: 'Bump and changelog using commitizen'
description: 'Create a commit bumping the version of your project and creating a changelog file'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'purple'
inputs:
  working-directory:
    description: 'Change to this directory before running'
    required: false
  dry_run:
    description: 'Run without creating commit, output to stdout'
    required: false
  prerelease:
    description: 'Set as prerelease version'
    required: false
  changelog:
    description: 'Create changelog when bumping the version'
    default: "true"
    required: false
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'master'
  extra_requirements:
    description: 'Extra commitizen dependencies like your custom plugins or rules'
    required: false
    default: ''
  changelog_increment_filename:
    description: 'Filename to store the incremented generated changelog. This is different to changelog as it only contains the changes for the just generated version'
    required: false
